quarkus.http.port=8080
quarkus.swagger-ui.always-include=true
quarkus.oidc.application-type=service
quarkus.oidc.auth-server-url=${KEYCLOAK_URL:http://localhost:8180/realms/fiapx}
quarkus.micrometer.export.prometheus.path=/q/metrics
mp.messaging.outgoing.processing-jobs.connector=smallrye-rabbitmq
mp.messaging.outgoing.processing-jobs.exchange.name=processing-jobs
mp.messaging.outgoing.processing-jobs.routing-key=accepted
fiapx.minio.url=${MINIO_URL:http://localhost:9000}
fiapx.minio.access-key=${MINIO_ACCESS_KEY:minio}
fiapx.minio.secret-key=${MINIO_SECRET_KEY:miniosecret}
